import { AppTheme } from "../../../contexts/ThemeContext";

export const createStyles = (theme: AppTheme) => ({
  mainContainer: {
    flex: 1,
    backgroundColor: theme.background,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    padding: 20,
  },
  card: {
    width: "100%" as const,
    backgroundColor: theme.card,
    borderRadius: 30,
    padding: 25,
    paddingTop: 70,
    alignItems: "center" as const,
    position: "relative" as const,
    elevation: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
  },
  logoContainer: {
    position: "absolute" as const,
    top: -55,
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: theme.card,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    borderWidth: 4,
    borderColor: theme.icono,
    zIndex: 10,
    elevation: 20,
    shadowColor: theme.icono,
    shadowOpacity: 0.4,
    shadowRadius: 10,
  },
  logo: {
    width: 100,
    height: 100,
    resizeMode: "contain" as const,
  },
  counterModule: {
    alignItems: "center" as const,
    marginBottom: 30,
  },
  circle: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: theme.containerBackground,
    borderWidth: 8,
    borderColor: theme.icono,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    marginBottom: 10,
  },
  number: {
    fontSize: 60,
    fontWeight: "900" as const,
    color: theme.text,
  },
  statusText: {
    fontSize: 18,
    fontWeight: "600" as const,
    color: theme.icono,
  },
  list: {
    width: "100%" as const,
    marginBottom: 25,
  },
  itemRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginBottom: 15,
    backgroundColor: theme.containerBackground,
    padding: 10,
    borderRadius: 15,
  },
  iconBackground: {
    width: 35,
    height: 35,
    borderRadius: 10,
    backgroundColor: theme.contactBadgeBg,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    marginRight: 12,
  },
  itemText: {
    color: theme.text,
    fontSize: 14,
    fontWeight: "500" as const,
  },
  cancelButton: {
    backgroundColor: theme.tabBackground,
    width: "100%" as const,
    paddingVertical: 15,
    borderRadius: 15,
    alignItems: "center" as const,
  },
  cancelText: {
    color: theme.headerText,
    fontWeight: "600" as const,
  },
});