import { AppTheme } from "../../../contexts/ThemeContext";

type Insets = { top: number; bottom: number; left: number; right: number };

// Recibe también el alto de pantalla y los insets (notch, barra de gestos, bordes laterales)
// para que nada quede pegado ni tapado por el sistema.
export const createStyles = (
  theme: AppTheme,
  width: number,
  height: number,
  insets: Insets,
) => {
  const isCompact = width < 360;
  const isWide = width >= 500;
  const horizontalPadding = Math.max(16, Math.min(width * 0.05, 32));
  const mapHeight = Math.round(Math.min(Math.max(height * 0.36, 220), 380));

  const sombra = {
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  };

  return {
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    content: {
      flexGrow: 1,
      paddingTop: insets.top + 16,
      paddingBottom: insets.bottom + 24,
      paddingLeft: horizontalPadding + insets.left,
      paddingRight: horizontalPadding + insets.right,
    },
    // Limita el ancho en tablets / horizontal y centra el contenido.
    wrap: {
      width: "100%" as const,
      maxWidth: 560,
      alignSelf: "center" as const,
    },

    // Encabezado
    badge: {
      alignSelf: "flex-start" as const,
      maxWidth: "100%" as const,
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 8,
      backgroundColor: theme.containerBackground,
      paddingHorizontal: 14,
      paddingVertical: 7,
      borderRadius: 20,
      marginBottom: 12,
    },
    badgeText: {
      flexShrink: 1,
      fontSize: 12,
      fontWeight: "700" as const,
      color: theme.icono,
    },
    title: {
      fontSize: isCompact ? 22 : isWide ? 30 : 26,
      fontWeight: "800" as const,
      color: theme.icono,
      textAlign: "center" as const,
    },
    subtitle: {
      fontSize: isCompact ? 13 : 15,
      color: theme.text,
      marginTop: 2,
      marginBottom: 14,
    },
    subtitleName: {
      fontWeight: "800" as const,
    },

    // Mapa pequeño (vista previa)
    mapCard: {
      height: mapHeight,
      borderRadius: 24,
      overflow: "hidden" as const,
      backgroundColor: theme.containerBackground,
      marginBottom: 14,
    },
    map: {
      width: "100%" as const,
      height: "100%" as const,
    },
    mapPlaceholder: {
      flex: 1,
      justifyContent: "center" as const,
      alignItems: "center" as const,
      gap: 10,
      padding: 20,
    },
    mapPlaceholderText: {
      color: theme.text,
      opacity: 0.7,
      fontSize: 13,
      textAlign: "center" as const,
    },
    pillUbicacion: {
      position: "absolute" as const,
      top: 12,
      left: 12,
      maxWidth: "68%" as const,
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 8,
      backgroundColor: theme.containerBackground,
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 16,
    },
    pillTitle: {
      fontSize: 11,
      fontWeight: "800" as const,
      color: theme.text,
    },
    pillSub: {
      fontSize: 9.5,
      color: theme.text,
      opacity: 0.65,
      marginTop: 1,
    },
    pillBarrioRow: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 3,
      marginTop: 2,
    },
    pillBarrio: {
      flexShrink: 1,
      fontSize: 9.5,
      fontWeight: "700" as const,
      color: theme.icono,
    },
    btnMaps: {
      position: "absolute" as const,
      bottom: 12,
      right: 12,
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 6,
      backgroundColor: theme.containerBackground,
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.contactDivider,
    },
    btnMapsText: {
      fontSize: 12,
      fontWeight: "700" as const,
      color: theme.icono,
    },

    // Pines numerados
    pin: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: theme.icono,
      opacity: 0.65,
      borderWidth: 2,
      borderColor: "#FFFFFF",
      justifyContent: "center" as const,
      alignItems: "center" as const,
    },
    pinText: {
      color: "#FFFFFF",
      fontSize: 11,
      fontWeight: "800" as const,
    },
    pinActual: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.icono,
      borderWidth: 3,
      borderColor: "#FFFFFF",
      justifyContent: "center" as const,
      alignItems: "center" as const,
      elevation: 6,
    },
    pinActualText: {
      color: "#FFFFFF",
      fontSize: 15,
      fontWeight: "900" as const,
    },

    // Tarjetas
    card: {
      backgroundColor: theme.containerBackground,
      borderRadius: 24,
      padding: 18,
      marginBottom: 14,
    },
    cardHeader: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      justifyContent: "space-between" as const,
      gap: 8,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.contactDivider,
    },
    cardHeaderLeft: {
      flexShrink: 1,
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 10,
    },
    cardIconWrap: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.card,
      justifyContent: "center" as const,
      alignItems: "center" as const,
    },
    cardTitle: {
      flexShrink: 1,
      fontSize: 16,
      fontWeight: "700" as const,
      color: theme.text,
    },
    liveBadge: {
      backgroundColor: theme.card,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    liveBadgeText: {
      fontSize: 11,
      fontWeight: "700" as const,
      color: theme.icono,
    },
    dataRow: {
      flexDirection: "row" as const,
      flexWrap: "wrap" as const,
      justifyContent: "space-between" as const,
      alignItems: "flex-start" as const,
      marginTop: 12,
      gap: 6,
    },
    dataLabel: {
      flexShrink: 1,
      fontSize: 13,
      color: theme.text,
      opacity: 0.65,
      fontWeight: "500" as const,
    },
    dataValueMono: {
      flexShrink: 1,
      fontSize: 13,
      fontWeight: "700" as const,
      color: theme.text,
      backgroundColor: theme.card,
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 8,
      fontVariant: ["tabular-nums" as const],
    },
    dataValue: {
      flexShrink: 1,
      fontSize: 12,
      fontWeight: "600" as const,
      color: theme.text,
      textAlign: "right" as const,
      marginTop: 2,
    },

    // Aviso de estado
    avisoCard: {
      flexDirection: "row" as const,
      alignItems: "flex-start" as const,
      gap: 12,
      backgroundColor: theme.containerBackground,
      borderRadius: 24,
      padding: 16,
      marginBottom: 14,
    },
    avisoIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.card,
      justifyContent: "center" as const,
      alignItems: "center" as const,
    },
    avisoTitle: {
      fontSize: 14,
      fontWeight: "800" as const,
      color: theme.icono,
    },
    avisoText: {
      fontSize: 12.5,
      lineHeight: 18,
      color: theme.text,
      marginTop: 3,
    },
    avisoBold: {
      fontWeight: "700" as const,
    },
    errorText: {
      fontSize: 12,
      color: "#C0392B",
      marginTop: 6,
    },

    // Historial (línea de tiempo)
    historialHeader: {
      flexDirection: "row" as const,
      flexWrap: "wrap" as const,
      alignItems: "center" as const,
      justifyContent: "space-between" as const,
      gap: 6,
      marginBottom: 16,
    },
    historialTitleRow: {
      flexShrink: 1,
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 8,
    },
    historialDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.icono,
    },
    historialSub: {
      fontSize: 11,
      color: theme.text,
      opacity: 0.55,
      fontWeight: "500" as const,
    },
    timeline: {
      paddingLeft: 22,
    },
    timelineLine: {
      position: "absolute" as const,
      left: 7,
      top: 8,
      bottom: 10,
      width: 2,
      backgroundColor: theme.contactDivider,
    },
    timelineItem: {
      flexDirection: "row" as const,
      justifyContent: "space-between" as const,
      alignItems: "flex-start" as const,
      gap: 8,
      marginBottom: 18,
    },
    timelineNode: {
      position: "absolute" as const,
      left: -22,
      top: 3,
      width: 16,
      height: 16,
      alignItems: "center" as const,
      justifyContent: "center" as const,
    },
    timelineNodeSmall: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: theme.icono,
      opacity: 0.55,
      borderWidth: 2,
      borderColor: theme.containerBackground,
    },
    timelineRowTop: {
      flexDirection: "row" as const,
      flexWrap: "wrap" as const,
      alignItems: "center" as const,
      gap: 8,
    },
    timelineTimeActual: {
      fontSize: 12,
      fontWeight: "800" as const,
      color: theme.icono,
    },
    timelineTime: {
      fontSize: 12,
      fontWeight: "600" as const,
      color: theme.text,
    },
    recienteTag: {
      fontSize: 9.5,
      fontWeight: "800" as const,
      textTransform: "uppercase" as const,
      color: theme.icono,
      backgroundColor: theme.card,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      overflow: "hidden" as const,
    },
    timelineCoords: {
      fontSize: 12,
      color: theme.text,
      opacity: 0.65,
      marginTop: 3,
    },
    timelineBarrioRow: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 3,
      marginTop: 3,
    },
    timelineBarrio: {
      flexShrink: 1,
      fontSize: 12,
      fontWeight: "600" as const,
      color: theme.icono,
    },
    timelineOffset: {
      fontSize: 11,
      fontWeight: "600" as const,
      color: theme.text,
      opacity: 0.5,
    },
    timelineActual: {
      fontSize: 11,
      fontWeight: "700" as const,
      color: theme.icono,
    },
    sinRegistros: {
      fontSize: 13,
      color: theme.text,
      opacity: 0.6,
      textAlign: "center" as const,
      paddingVertical: 8,
    },

    consejo: {
      textAlign: "center" as const,
      fontSize: 12,
      color: theme.text,
      opacity: 0.65,
      fontWeight: "500" as const,
      paddingHorizontal: 12,
      marginVertical: 4,
    },
    callButton: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      justifyContent: "center" as const,
      gap: 10,
      backgroundColor: theme.containerBackground,
      borderWidth: 1.5,
      borderColor: theme.icono,
      borderRadius: 18,
      paddingVertical: 14,
      marginTop: 14,
    },
    callText: {
      fontSize: 16,
      fontWeight: "800" as const,
      color: theme.icono,
    },

    // Ventana emergente del mapa
    modalContainer: {
      flex: 1,
      backgroundColor: theme.background,
    },
    modalMap: {
      flex: 1,
    },
    modalTopBar: {
      position: "absolute" as const,
      top: insets.top + 10,
      left: insets.left + 12,
      right: insets.right + 12,
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 10,
    },
    modalCloseBtn: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 6,
      height: 46,
      paddingHorizontal: 16,
      borderRadius: 23,
      backgroundColor: theme.containerBackground,
      ...sombra,
    },
    modalCloseText: {
      fontSize: 13,
      fontWeight: "700" as const,
      color: theme.icono,
    },
    modalTitlePill: {
      flex: 1,
      minHeight: 46,
      justifyContent: "center" as const,
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 23,
      backgroundColor: theme.containerBackground,
      ...sombra,
    },
    modalTitle: {
      fontSize: 12,
      fontWeight: "800" as const,
      color: theme.text,
    },
    modalSub: {
      fontSize: 10.5,
      color: theme.text,
      opacity: 0.65,
    },
    modalFitBtn: {
      position: "absolute" as const,
      bottom: insets.bottom + 16,
      right: insets.right + 16,
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: theme.containerBackground,
      justifyContent: "center" as const,
      alignItems: "center" as const,
      ...sombra,
    },
    modalInfo: {
      position: "absolute" as const,
      bottom: insets.bottom + 16,
      left: insets.left + 16,
      right: insets.right + 82,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 18,
      backgroundColor: theme.containerBackground,
      ...sombra,
    },
    modalInfoText: {
      fontSize: 12,
      fontWeight: "700" as const,
      color: theme.text,
    },
    modalInfoBarrio: {
      fontSize: 12,
      fontWeight: "600" as const,
      color: theme.icono,
      marginTop: 2,
    },
  };
};